let suggestions=[
"front end web developer",
"full stack web developer",
"learn kotlin",
"become an ios developer",
"ai programming with python",
"artifical intelligence for trading",
"become a data scientist",
"data science with aws",
"data structure and algorithms",
"Deep Learning",
"UX Designer",
"SQL",
"Machine Learning DevOps Engineer",
"React",
"AI for Healthcare",
"Data Product Manager",
"Java Programming",
"Android Kotlin Developer",
"web design for everybody",
"intrduction to web development",
"meta andriod developer",
"andriod app dvelopment specialization",
"machine learning specialization",
"ibm machine learning",
"ibm data science",
"introduction to data science specialization",
"oops java programming and dsa beyond specialization",
"meta back end developer professional certificate",
"algorithms part 01",
"introduction to frond end development",
"build a full website using wordpress",
"Responsive Website Development and design specialization",
"The full stack development",
"google ux design ",
"ui/ux design",
"full stack web developer(HTML,CSS,JS)",
"the web developer bootcamp 2023",
"ios and swift: the complete ios app development",
"the complete andriod 12 and kotlin course",
"statistics for ai and ml developers",
"ai and ml in the field of mathematics",
"the data science course 2023",
"complete machine learning and data science",
"dsa in java",
"java dsa and algorithms masterclass",
"100 days of code:web development bootcamp 2023",
"the ultimate full stack web development code",
"the complete web developer course 3.0",
"ultimate web designer and web developer course",
"complete web and mobile designer(ui/ux)",
"figma ui/ux designer",
"master digital prodcut design",
"ui/ux design hybrid figma to html css",
"the complete sql bootcamp",
"the ultimate sql bootcamp 2023",

];
